# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

inhibit_all_warnings!

target "MAF" do

pod 'Bolts', '~> 1.1'
pod 'CrittercismSDK'
pod 'Parse', '~> 1.2'
pod 'PNChart', :git => 'https://github.com/mhahn/PNChart.git'
pod 'XLForm', '~> 2.0'
pod 'MHPrettyDate'
pod 'MRProgress', '~> 0.6'
pod 'UICountingLabel'
pod 'pop'

end

target "MAFTests" do

end

