# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "MAF" do

pod 'Bolts', '~> 1.1'
pod 'CrittercismSDK'
pod 'Parse', '~> 1.2'
pod 'XLForm', '~> 2.0'
pod 'MHPrettyDate'

end

target "MAFTests" do

end

