# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "MAF" do

pod 'Bolts', '~> 1.1'
pod 'CrittercismSDK'
pod 'FXForms', '~> 1.1.6'
pod 'Parse', '~> 1.2'

end

target "MAFTests" do

end

